# Generated by Django 5.1 on 2024-08-11 23:21

import django.db.models.deletion
import spa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0001_let_begin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.EmailField(max_length=128),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(upload_to=spa.models.upload_file, validators=[spa.models.validate_file_size])),
                ('user_post', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spa.post')),
            ],
        ),
    ]
